### ISSUE TITLE
Not an Issue, but a few questions?

### ISSUE THREAD

**Issue by ghost** [jertel/p37-ec#4]
Hello,
Your work inspired many of us to use Linux in Gigabyte Aero, Aorus laptops. I guess you have been running this custom-made control application for long time. How long you have been using this with Gigabyte laptop, and how is it working till today, if I may?

**Comment by jertel** [comment]
I have since retired that laptop. But I did use the p37-ec program to control the fans under Linux, for the duration that I used it as my primary workstation, which was roughly 4 years. Thanks for your interest.

**Comment by ghost** [comment]
Thank you for the reply. I heard that ec_sys is not recommended due to the security risk. Is that true?

**Comment by jertel** [comment]
Yes, there are security concerns with ec_sys. I believe the P-37x had a nuance where, from a cold-boot, the fans will default to high speed, but after the EC was configured to adjust the fan speed, a subsequent reboot would retain that altered mode. Alternatively, consider unloading unnecessary modules to reduce risk exposure.

**Comment by ghost** [comment]
Thank you so much for the reply. Sorry, I just keep asking questions, although I mention one question. I am using Fedora 36 in my Gigabyte Aero laptop. Looks like Fedora has not shipped the ec_sys and there is no way to install it. Do you have any suggestion about that? Do you have any plan to write a kernel module for this?
